// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/fetch-page-seo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var UA = "Mozilla/5.0 (compatible; SitemapScoutMCP/1.0)";
var TIMEOUT_MS = 15e3;
function isPrivateHost(host) {
  const h = host.toLowerCase();
  if (h === "localhost" || h === "::1" || h.endsWith(".localhost") || h.endsWith(".local") || h.endsWith(".internal")) return true;
  if (/^(127\.|10\.|192\.168\.|169\.254\.|0\.)/.test(h)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(h)) return true;
  if (/^(fc|fd)[0-9a-f]{2}:/i.test(h) || /^fe80:/i.test(h)) return true;
  return false;
}
function pickAttr(tag, attr) {
  const re = new RegExp(`\\b${attr}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s>]+))`, "i");
  const m = tag.match(re);
  return m ? (m[1] ?? m[2] ?? m[3])?.trim() : void 0;
}
function extractMeta(html, name) {
  const re = new RegExp(`<meta\\b[^>]*\\b(?:name|property)\\s*=\\s*["']${name}["'][^>]*>`, "i");
  const tag = html.match(re)?.[0];
  return tag ? pickAttr(tag, "content") : void 0;
}
function extractAll(html, re) {
  const out = [];
  let m;
  while ((m = re.exec(html)) !== null) out.push(m[1].trim());
  return out;
}
var fetch_page_seo_default = defineTool({
  name: "fetch_page_seo",
  title: "Fetch page SEO",
  description: "Fetch a public URL and extract SEO metadata: HTTP status, final URL after redirects, title, meta description, canonical, robots directive, H1s, Open Graph and Twitter tags.",
  inputSchema: {
    url: z.string().url().describe("Absolute http(s) URL to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    let target;
    try {
      target = new URL(url);
    } catch {
      return { content: [{ type: "text", text: "Invalid URL" }], isError: true };
    }
    if (target.protocol !== "http:" && target.protocol !== "https:") {
      return { content: [{ type: "text", text: "Only http/https URLs are allowed" }], isError: true };
    }
    if (isPrivateHost(target.hostname)) {
      return { content: [{ type: "text", text: "Private or internal hosts are not allowed" }], isError: true };
    }
    try {
      const res = await fetch(target.toString(), {
        redirect: "follow",
        headers: { "User-Agent": UA, Accept: "text/html,application/xhtml+xml" },
        signal: AbortSignal.timeout(TIMEOUT_MS)
      });
      const contentType = res.headers.get("content-type") ?? "";
      const html = /text\/html|application\/xhtml/i.test(contentType) ? await res.text() : "";
      const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim();
      const description = extractMeta(html, "description");
      const robots = extractMeta(html, "robots");
      const canonicalTag = html.match(/<link\b[^>]*\brel\s*=\s*["']canonical["'][^>]*>/i)?.[0];
      const canonical = canonicalTag ? pickAttr(canonicalTag, "href") : void 0;
      const h1s = extractAll(html, /<h1\b[^>]*>([\s\S]*?)<\/h1>/gi).map((s) => s.replace(/<[^>]+>/g, "").trim());
      const result = {
        requestedUrl: url,
        finalUrl: res.url,
        status: res.status,
        contentType,
        title,
        description,
        canonical,
        robots,
        h1: h1s.slice(0, 5),
        openGraph: {
          title: extractMeta(html, "og:title"),
          description: extractMeta(html, "og:description"),
          image: extractMeta(html, "og:image"),
          type: extractMeta(html, "og:type"),
          url: extractMeta(html, "og:url")
        },
        twitter: {
          card: extractMeta(html, "twitter:card"),
          title: extractMeta(html, "twitter:title"),
          description: extractMeta(html, "twitter:description"),
          image: extractMeta(html, "twitter:image")
        }
      };
      return {
        content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        structuredContent: result
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Fetch failed: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/fetch-robots-txt.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var UA2 = "Mozilla/5.0 (compatible; SitemapScoutMCP/1.0)";
function isPrivateHost2(host) {
  const h = host.toLowerCase();
  if (h === "localhost" || h === "::1" || h.endsWith(".localhost") || h.endsWith(".local") || h.endsWith(".internal")) return true;
  if (/^(127\.|10\.|192\.168\.|169\.254\.|0\.)/.test(h)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(h)) return true;
  if (/^(fc|fd)[0-9a-f]{2}:/i.test(h) || /^fe80:/i.test(h)) return true;
  return false;
}
var fetch_robots_txt_default = defineTool2({
  name: "fetch_robots_txt",
  title: "Fetch robots.txt",
  description: "Fetch the robots.txt file for a domain and return its raw content plus discovered sitemap URLs.",
  inputSchema: {
    domain: z2.string().min(1).describe('Domain or origin, e.g. "example.com" or "https://example.com".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ domain }) => {
    let origin;
    try {
      const u = new URL(domain.startsWith("http") ? domain : `https://${domain}`);
      origin = u.origin;
      if (isPrivateHost2(u.hostname)) {
        return { content: [{ type: "text", text: "Private or internal hosts are not allowed" }], isError: true };
      }
    } catch {
      return { content: [{ type: "text", text: "Invalid domain" }], isError: true };
    }
    const target = `${origin}/robots.txt`;
    try {
      const res = await fetch(target, {
        redirect: "follow",
        headers: { "User-Agent": UA2, Accept: "text/plain,*/*" },
        signal: AbortSignal.timeout(15e3)
      });
      const text = await res.text();
      const sitemaps = Array.from(text.matchAll(/^\s*sitemap\s*:\s*(\S+)/gim)).map((m) => m[1]);
      const result = { url: target, status: res.status, finalUrl: res.url, content: text, sitemaps };
      return {
        content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        structuredContent: result
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Fetch failed: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-sitemap-urls.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var UA3 = "Mozilla/5.0 (compatible; SitemapScoutMCP/1.0)";
var MAX_URLS = 1e3;
var MAX_INDEX_CHILDREN = 20;
function isPrivateHost3(host) {
  const h = host.toLowerCase();
  if (h === "localhost" || h === "::1" || h.endsWith(".localhost") || h.endsWith(".local") || h.endsWith(".internal")) return true;
  if (/^(127\.|10\.|192\.168\.|169\.254\.|0\.)/.test(h)) return true;
  if (/^172\.(1[6-9]|2\d|3[01])\./.test(h)) return true;
  if (/^(fc|fd)[0-9a-f]{2}:/i.test(h) || /^fe80:/i.test(h)) return true;
  return false;
}
async function fetchXml(url) {
  const u = new URL(url);
  if (u.protocol !== "http:" && u.protocol !== "https:") throw new Error("Only http/https URLs allowed");
  if (isPrivateHost3(u.hostname)) throw new Error("Private hosts not allowed");
  const res = await fetch(url, {
    redirect: "follow",
    headers: { "User-Agent": UA3, Accept: "application/xml,text/xml,*/*" },
    signal: AbortSignal.timeout(15e3)
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return await res.text();
}
function extractLocs(xml, tag) {
  const re = new RegExp(`<${tag}>[\\s\\S]*?<loc>\\s*([^<]+?)\\s*</loc>[\\s\\S]*?</${tag}>`, "gi");
  const out = [];
  let m;
  while ((m = re.exec(xml)) !== null) out.push(m[1].trim());
  return out;
}
var list_sitemap_urls_default = defineTool3({
  name: "list_sitemap_urls",
  title: "List sitemap URLs",
  description: "Fetch a sitemap XML (or sitemap index) and return the URLs it contains. Recurses one level into sitemap indexes.",
  inputSchema: {
    sitemapUrl: z3.string().url().describe("Full URL to a sitemap.xml or sitemap index."),
    limit: z3.number().int().min(1).max(MAX_URLS).default(200).describe("Max URLs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ sitemapUrl, limit }) => {
    try {
      const xml = await fetchXml(sitemapUrl);
      const isIndex = /<sitemapindex\b/i.test(xml);
      const collected = [];
      const childSitemaps = [];
      if (isIndex) {
        const children = extractLocs(xml, "sitemap").slice(0, MAX_INDEX_CHILDREN);
        childSitemaps.push(...children);
        for (const child of children) {
          if (collected.length >= limit) break;
          try {
            const childXml = await fetchXml(child);
            for (const loc of extractLocs(childXml, "url")) {
              collected.push(loc);
              if (collected.length >= limit) break;
            }
          } catch {
          }
        }
      } else {
        for (const loc of extractLocs(xml, "url")) {
          collected.push(loc);
          if (collected.length >= limit) break;
        }
      }
      const result = {
        sitemapUrl,
        isIndex,
        childSitemaps,
        count: collected.length,
        urls: collected
      };
      return {
        content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
        structuredContent: result
      };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { content: [{ type: "text", text: `Failed to load sitemap: ${msg}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sitemap-scout-mcp",
  title: "Sitemap Scout MCP",
  version: "0.1.0",
  instructions: "Sitemap Scout tools for technical SEO. Use `fetch_page_seo` to inspect a single URL's metadata, `fetch_robots_txt` to read a site's robots.txt and discover sitemaps, and `list_sitemap_urls` to enumerate URLs from a sitemap or sitemap index.",
  tools: [fetch_page_seo_default, fetch_robots_txt_default, list_sitemap_urls_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
